name: Dwarves vs Zombies
main: me.andre111.dvz.DvZ
version: 1.5.1
website: http://andre111.bplaced.net/
author: andre111

softdepend: [DisguiseCraft]

commands:
   dvztest:
      description: Testing some stuff(do not use this)
      aliases: []
      usage: /<command>
      permission: dvz.test
   dvz:
      description: The Main command
      aliases: []
      usage: /<command> [subcommand] <subcommand_args>
   dvz_start:
      description: Start the Game in [Time]
      aliases: [d_start]
      usage: /<command> [gameID_default_0] <time> <minutes_till_assasins> <assasins> <maxdeaths>
      permission: dvz.start
   dvz_dwarf:
      description: Set the Spawnpoints for the Dwarves
      aliases: [d_dwarf]
      usage: /<command> <GameID_default_dummygame>
      permission: dvz.setspawn
   dvz_monster:
      description: Set the Spawnpoints for the Monsters
      aliases: [d_monster]
      usage: /<command> <GameID_default_dummygame>
      permission: dvz.setspawn
   dvz_info:
      description: Get Information about the Gamestate
      aliases: [d_info]
      usage: /<command> [gameID_default_0] 
      permission: dvz.info
   dvz_reset:
      description: Reset all Playerstates
      aliases: [d_reset]
      usage: /<command> [gameID_default_0] 
      permission: dvz.reset
   dvz_monument:
      description: Create the Dwarf Monument at your current position
      aliases: [d_monument]
      usage: /<command> <GameID_default_dummygame>
      permission: dvz.monument
   dvz_dragon:
      description: Turns you into a dragon
      aliases: [d_dragon]
      usage: /<command> [type]
      permission: dvz.dragon
   dvz_add:
      description: Add a Player to the game even after it has been started
      aliases: [d_add]
      usage: /<command> [gameID_default_0] [Playername]
      permission: dvz.add
   dvz_assasin:
      description: Chose random Players to be Assasins
      aliases: [d_assasin]
      usage: /<command> [gameID_default_0] <Count>
      permission: dvz.assasin
   dvz_join:
      description: Join the Game
      aliases: [d_join]
      usage: /<command> [gameID_default_0]
      permission: dvz.join
   dvz_joini:
      description: Join the Game ignoring Items in your Inventory
      aliases: [d_joini]
      usage: /<command> [gameID_default_0]
      permission: dvz.join
   dvz_leave:
      description: Leave the game(only possible in the lobby)
      aliases: [d_leave]
      usage: /<command>
      permission: dvz.leave
   dvz_saveworld:
      description: Save the current world
      aliases: [dvz_save,d_saveworld,d_save]
      usage: /<command>
      permission: dvz.save
   dvz_createworld:
      description: Saves the current world as a automatic World
      aliases: [dvz_create,d_createworld,d_create]
      usage: /<command>
      permission: dvz.save
   dvz_release:
      description: Releases the Monsters
      aliases: [d_release]
      usage: /<command> [gameID_default_0]
      permission: dvz.release

permissions:
   dvz.*:
      description: Gives you all DvZ permissions
      default: op
      children:
         dvz.start: true
         dvz.setspawn: true
         dvz.info: true
         dvz.reset: true
         dvz.monument: true
         dvz.dragon: true
         dvz.add: true
         dvz.assasin: true
         dvz.join: true
         dvz.leave: true
         dvz.save: true
         dvz.release: true
         dvz.dwarves.*: true
         dvz.monster.*: true
   dvz.start:
      description: Starting the Game
      default: op
   dvz.setspawn:
      description: Set the Spawnlocations dor Dwarves/Monsters
      default: op
   dvz.info:
      description: Get Information about the Gamestate
      default: true
   dvz.reset:
      description: Reset all Playerstates
      default: op
   dvz.monument:
      description: Create the Dwarf Monument at your current position
      default: op
   dvz.dragon:
      description: Turns you into a dragon
      default: op
   dvz.add:
      description: Add a Player to the game even after it has been started
      default: op
   dvz.assasin:
      description: Chose random Players to be Assasins
      default: op
   dvz.join:
      description: Join the Game
      default: true
   dvz.leave:
      description: Leave the game(only possible in the lobby)
      default: true
   dvz.save:
      description: Save the current world
      default: op
   dvz.release:
      description: Releases the Monsters
      default: op
   dvz.test:
      description: Testing some stuff(do not use this)
      default: op
   # dwarves
   dvz.dwarves.*:
      description: Gives permission to all dwarf classes
      default: true
      children:
         dvz.dwarves.1: true
         dvz.dwarves.2: true
         dvz.dwarves.3: true
         dvz.dwarves.4: true
         dvz.dwarves.5: true
         dvz.dwarves.6: true
         dvz.dwarves.7: true
         dvz.dwarves.8: true
         dvz.dwarves.9: true
         dvz.dwarves.10: true
   dvz.dwarves.1:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.2:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.3:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.4:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.5:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.6:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.7:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.8:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.9:
      description: Gives permission to the dwarf class
      default: true
   dvz.dwarves.10:
      description: Gives permission to the dwarf class
      default: true
   # monsters
   dvz.monster.*:
      description: Gives permission to all monster classes
      default: true
      children:
         dvz.monster.0: true
         dvz.monster.1: true
         dvz.monster.2: true
         dvz.monster.3: true
         dvz.monster.4: true
         dvz.monster.5: true
         dvz.monster.6: true
         dvz.monster.7: true
         dvz.monster.8: true
         dvz.monster.9: true
         dvz.monster.10: true
         dvz.monster.11: true
         dvz.monster.12: true
         dvz.monster.13: true
         dvz.monster.14: true
         dvz.monster.15: true
         dvz.monster.16: true
         dvz.monster.17: true
         dvz.monster.18: true
         dvz.monster.19: true
   dvz.monster.0:
      description: Gives permission to the monster class
      default: true
   dvz.monster.1:
      description: Gives permission to the monster class
      default: true
   dvz.monster.2:
      description: Gives permission to the monster class
      default: true
   dvz.monster.3:
      description: Gives permission to the monster class
      default: true
   dvz.monster.4:
      description: Gives permission to the monster class
      default: true
   dvz.monster.5:
      description: Gives permission to the monster class
      default: true
   dvz.monster.6:
      description: Gives permission to the monster class
      default: true
   dvz.monster.7:
      description: Gives permission to the monster class
      default: true
   dvz.monster.8:
      description: Gives permission to the monster class
      default: true
   dvz.monster.9:
      description: Gives permission to the monster class
      default: true
   dvz.monster.10:
      description: Gives permission to the monster class
      default: true
   dvz.monster.11:
      description: Gives permission to the monster class
      default: true
   dvz.monster.12:
      description: Gives permission to the monster class
      default: true
   dvz.monster.13:
      description: Gives permission to the monster class
      default: true
   dvz.monster.14:
      description: Gives permission to the monster class
      default: true
   dvz.monster.15:
      description: Gives permission to the monster class
      default: true
   dvz.monster.16:
      description: Gives permission to the monster class
      default: true
   dvz.monster.17:
      description: Gives permission to the monster class
      default: true
   dvz.monster.18:
      description: Gives permission to the monster class
      default: true
   dvz.monster.19:
      description: Gives permission to the monster class
      default: true